### PR TITLE
docker: Build multiarch images

### PR DESCRIPTION
**Pull request by MarcelWaldvogel**
See https://gitlab.nic.cz/knot/knot-dns/-/issues/718

(The file is now called `Makefile.docker`, as `Makefile.dm` was even less self-explanatory.)

### CODE REVIEW

**Comment by salzmdan** [comment]
Do I understand correctly that the resulting Docker image will be 4 times bigger?

**Comment by MarcelWaldvogel** [comment]
The local storage consumption on the build server as well as the amount of data transmitted to the DockerHub (and stored there) will indeed be 4 times as big. (And the build time will be some 10x longer, due to running everything in emulation, unless you have a native hardware available and include that as part of the build process; however, I have never done that myself, I just let the multiarch build run, after I am happy with the native build.)

However, any machine doing a "docker pull" (the client) or the like will only download a few hundred bytes more, namely the Manifest, which will point to the four individual images for the four platforms. The client will then automatically and transparently select the right image. The same process happens as part of the `FROM debian:stable-slim` in the `Dockerfile`. On https://hub.docker.com/_/debian?tab=tags&page=1&ordering=last_updated, you can see that `debian:stable-slim` consist of 8 platforms. But any client will only download the most appropriate platform.

**Comment by salzmdan** [comment]
Thanks for the explanation!

**Comment by salzmdan** [comment]
In progress, stay tuned!

**Comment by MarcelWaldvogel** [comment]
BTW: Will then there also be a `cznic/knot:3.0` tag for docker? I try to avoid going for `latest`, but 3.0 is so much greater than 2.8, … (and I rely on 3.0 features). A big thanks, BTW! :+1:

**Comment by salzmdan** [comment]
@MarcelWaldvogel Could you test `docker pull cznic/knot:master-test` - multiarch build based on Debian Bullseye tiny and proper libbpf

**Comment by salzmdan** [comment]
I have slightly modified your Makefile. Resolved by https://gitlab.nic.cz/knot/knot-dns/-/commit/a87fcc160cf7cc34bc93bb1d339a5e802b4751b6
Thanks!

**Pull request closed without merging**
