### PR TITLE
support for requiring valid stapled OCSP response

### PR DESCRIPTION
**Pull request by derschultz**
This change adds a new option (require-stapled) to kdig, which makes it so that kdig requires the server to send back a valid stapled OCSP response for the server's certificate when connecting via TLS.

### CODE REVIEW

**Comment by salzmdan** [comment]
I have created a branch for this MR in our gitlab https://gitlab.labs.nic.cz/knot/knot-dns/tree/kdig_ocsp

**Comment by salzmdan** [comment]
@derschultz I would like to rename the option to be more evident it relates to TLS and OCSP. What about `[+no]tls-ocsp`?

**Comment by vcunat** [comment]
What about a compromise `[+no]tls-ocsp-stapling`?  That's unambiguous, right?

**Comment by derschultz** [comment]
I think that OCSP can be left out (as "stapling" has a specific meaning in the context of TLS), but that 'require' needs to be there, to emphasize the fact that we require a valid OCSP response when using this option. So, how about `[+no]tls-require-stapling`?

**Comment by derschultz** [comment]
You're correct. I take back my objection. `[+no]tls-ocsp-stapling` is a fine option name.

**Comment by salzmdan** [comment]
`[+no]tls-ocsp-stapling` sounds good. As I don't like the `OCSP_VALID_PERIOD` constant, the parameter could have an optional value with the default 7 days? Does it make sense with the option name? :thinking:

**Comment by derschultz** [comment]
Sure. `+tls-ocsp-stapling=3` could signify that OCSP responses older than 3 days are considered invalid, while `+tls-ocsp-stapling` could signfiy that OCSP responses older than the default of 7 days are considered invalid.

**Comment by salzmdan** [comment]
@derschultz could you please take a look at my changes? https://gitlab.labs.nic.cz/knot/knot-dns/commits/kdig_ocsp
My problem is that I cannot verify functionality of this feature :-)

**Comment by derschultz** [comment]
The changes in the branch you specify look good, and I have checked them out, built them, and validated that they work as expected w.r.t. OCSP stapling/valid dates.

**Comment by salzmdan** [comment]
@derschultz thank you! Merged.

**Pull request closed without merging**
